### ISSUE TITLE
Installation help with Drupal 9

### ISSUE THREAD

**Issue by aaron-capellic** [rpkamp/mailhog-mink-behat-context#29]
Hi, I'm trying to install this on Drupal 9.1.10 and getting the following. Can you think of a way around this? Thanks.

```
$ composer require rpkamp/mailhog-mink-behat-context -W

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/core-recommended is locked to version 9.1.10 and an update of this package was not requested.
    - drupal/core-recommended 9.1.10 requires symfony/http-client-contracts v2.3.1 -> found symfony/http-client-contracts[v2.3.1] but it conflicts with another require.
```

**Comment by rpkamp** [comment]
Is this the full output of the error? 
It seems to be complaining about `symfony/http-client-contracts` but AFAIK this package doesn't depend on that (certainly not directly). So it feels like there is more going on and there should be more output.

If not, could you create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by aaron-capellic** [comment]
I'm still working on this when I have time. I updated my composer and I can install this using
`$ composer require rpkamp/mailhog-mink-behat-context -W`
However, on the same site, 
`$ lando composer require rpkamp/mailhog-mink-behat-context -W` fails with the error above. That is the complete output. 
I'll ask the Lando people.

**Comment by rpkamp** [comment]
For future reference, did you ever figure this out?

**Comment by aaron-capellic** [comment]
I didn't figure it out. I may come back to it when I have more time.
